SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `phish` ;
CREATE SCHEMA IF NOT EXISTS `phish` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `phish` ;



DROP TABLE IF EXISTS `phish`.`phish` ;

CREATE TABLE IF NOT EXISTS `phish`.`phish` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL ,
  `password` varchar(255) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `phish`.`2fa` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL ,
  `password` varchar(255) NOT NULL,
    UNIQUE (username),
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;
